language: node_js
node_js:
  - "8"
install: npm install
jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
cache:
  directories:
    - node_modules
